apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: vote
spec:
  type: LoadBalancer
  selector:
    app: result
  ports:
  - port: 5001
    name: result-service 
    targetPort: 80
    nodePort: 31001
