apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: vote
spec:
  type: LoadBalancer
  selector:
    app: vote
  ports:
  - port: 5000
    name: vote-service 
    targetPort: 80
    nodePort: 31000
